### ISSUE TITLE
Downloading of tracks for Offline mode fails

### ISSUE THREAD

**Issue by therightprofile** [lgruen/open-apollo-server#2]
Hi there, thank you for putting this together, it's very helpful. 

I was able to get open-apollo up and running on my watch but the downloading of tracks for offline access is very slow and it fails most of the time. 

Any idea what the reason could be? The cloud functions' logs look OK.

**Comment by planecore** [comment]
Doesn't work for me as well.

**Comment by kristofferR** [comment]
Make sure you are using rafaelmaeuer's updated open-apollo, and not the old one.

https://github.com/rafaelmaeuer/open-apollo

**Comment by ascopetoni** [comment]
The updated version seems to work fine. I am now able to download songs in a decent amout of time, thanks for the tip!
